name: Python unittest

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  python_unittest:
    name: Python unittest

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    # Setup.
    - uses: actions/checkout@v6
    - name: Install Dependencies
      run: pip install ruff sphinx build setuptools

    # Check.
    - name: Ruff Check
      run: ruff check --output-format=github
    - name: Ruff Format Check
      run: ruff format --check

    - name: Python Unittest
      run: python3 -m unittest --verbose

    # Docs.
    - name: Sphinx Build
      run: python -m sphinx.cmd.build --builder html . _build --fresh-env --fail-on-warning
      working-directory: docs

    # Package.
    - name: Install Folder
      run: pip install . --force-reinstall

    - name: Build Package
      run: python -m build

    - name: Install sdist
      run: pip install dist/pygrametl-*.tar.gz --force-reinstall

    - name: Install wheel
      run: pip install dist/pygrametl-*.whl --force-reinstall

    - name: Jython Imports
      shell: bash
      run: |
      	   curl -O https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.4/jython-standalone-2.7.4.jar
	   export JYTHONPATH=$(python -c 'import site; print(site.getsitepackages()[0])')
	   # pygrametl.drawntabletesting uses sqlite3 and pygrametl.datasources uses **kwds and sqlite3.
	   java -jar jython-standalone-2.7.4.jar -c "import pygrametl; import pygrametl.aggregators; import pygrametl.FIFODict; import pygrametl.JDBCConnectionWrapper; import pygrametl.jythonmultiprocessing; import pygrametl.parallel; import pygrametl.steps; import pygrametl.tables"