name: Python unittest

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  python_unittest:
    name: Python unittest

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v6
    - name: Install Ruff and Sphinx
      run: pip install ruff sphinx

    - name: Ruff Check
      run: ruff check --output-format=github
    - name: Ruff Format Check
      run: ruff format --check --preview --output-format=github

    - name: Python Unittest
      run: python3 -m unittest --verbose

    - name: Sphinx (Ubuntu/macOS)
      if: runner.os != 'Windows'
      run: make html
      working-directory: docs
    - name: Sphinx (Windows)
      if: runner.os == 'Windows'
      run: make.bat hmtl
      working-directory: docs
