name: Python unittest

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  python_unittest:
    name: Python unittest

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    # Setup.
    - uses: actions/checkout@v6
    - name: Install Dependencies
      run: python -m pip install ruff vermin sphinx build setuptools

    # Check.
    - name: Ruff Check
      run: ruff check --output-format=github

    - name: Ruff Format Check
      run: ruff format --check

    - name: Python Unittest
      run: python -m unittest --verbose

    - name: Vermin Violations
      run: vermin --quiet  --target=3.4 --violations .

    # Docs.
    - name: Sphinx Build
      run: python -m sphinx.cmd.build --builder html . _build --fresh-env --fail-on-warning
      working-directory: docs

    # Package.
    - name: Install Folder
      run: pip install . --force-reinstall

    - name: Build Package
      run: python -m build

    - name: Install sdist
      run: pip install pygrametl-2.8.tar.gz --force-reinstall
      working-directory: dist

    - name: Install wheel
      run: pip install pygrametl-2.8-py3-none-any.whl --force-reinstall
      working-directory: dist

    - name: Jython Imports
      shell: bash
      run: |
        curl -O https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.4/jython-standalone-2.7.4.jar
        export JYTHONPATH=$(python -c "import site; print(site.getsitepackages()[0])")
        # pygrametl.drawntabletesting uses sqlite3 heavily and was not developed with Python 2.7 support in mind.
        java -jar jython-standalone-2.7.4.jar -c "import pygrametl; import pygrametl.aggregators; pygrametl.datasources; import pygrametl.FIFODict; import pygrametl.JDBCConnectionWrapper; import pygrametl.jythonmultiprocessing; import pygrametl.parallel; import pygrametl.steps; import pygrametl.tables"